### ISSUE TITLE
KeyError: 0  in video_detector.py

### ISSUE THREAD

**Issue by m3m3-chan** [richaagrawa/Person-Detection-in-Various-Postures#2]
Hi , 
Thanks for sharing this work! 
When I run the  video_detector.py I get the following error:
```
Traceback (most recent call last):
  File "video_detector.py", line 37, in <module>
    clf = joblib.load(os.path.join(model_path, 'svm.model'))
  File "C:\Users\m\Anaconda3\envs\py5\lib\site-packages\joblib\numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\m\Anaconda3\envs\py5\lib\site-packages\joblib\numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "C:\Users\m\Anaconda3\envs\py5\lib\pickle.py", line 1043, in load
    dispatch[key[0]](self)
KeyError: 0
```
Any way to solve this?

Thanks,

**Comment by SimitTomar** [comment]
Getting the same error, any help will be appreciated.

Thanks,
